/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Video } from "./Video";
import { VideoCountArgs } from "./VideoCountArgs";
import { VideoFindManyArgs } from "./VideoFindManyArgs";
import { VideoFindUniqueArgs } from "./VideoFindUniqueArgs";
import { CreateVideoArgs } from "./CreateVideoArgs";
import { UpdateVideoArgs } from "./UpdateVideoArgs";
import { DeleteVideoArgs } from "./DeleteVideoArgs";
import { CommentFindManyArgs } from "../../comment/base/CommentFindManyArgs";
import { Comment } from "../../comment/base/Comment";
import { LikeFindManyArgs } from "../../like/base/LikeFindManyArgs";
import { Like } from "../../like/base/Like";
import { ReportFindManyArgs } from "../../report/base/ReportFindManyArgs";
import { Report } from "../../report/base/Report";
import { Product } from "../../product/base/Product";
import { VideoService } from "../video.service";
@graphql.Resolver(() => Video)
export class VideoResolverBase {
  constructor(protected readonly service: VideoService) {}

  async _videosMeta(
    @graphql.Args() args: VideoCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Video])
  async videos(@graphql.Args() args: VideoFindManyArgs): Promise<Video[]> {
    return this.service.videos(args);
  }

  @graphql.Query(() => Video, { nullable: true })
  async video(
    @graphql.Args() args: VideoFindUniqueArgs
  ): Promise<Video | null> {
    const result = await this.service.video(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Video)
  async createVideo(@graphql.Args() args: CreateVideoArgs): Promise<Video> {
    return await this.service.createVideo({
      ...args,
      data: {
        ...args.data,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Video)
  async updateVideo(
    @graphql.Args() args: UpdateVideoArgs
  ): Promise<Video | null> {
    try {
      return await this.service.updateVideo({
        ...args,
        data: {
          ...args.data,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Video)
  async deleteVideo(
    @graphql.Args() args: DeleteVideoArgs
  ): Promise<Video | null> {
    try {
      return await this.service.deleteVideo(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Comment], { name: "comments" })
  async findComments(
    @graphql.Parent() parent: Video,
    @graphql.Args() args: CommentFindManyArgs
  ): Promise<Comment[]> {
    const results = await this.service.findComments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Like], { name: "likes" })
  async findLikes(
    @graphql.Parent() parent: Video,
    @graphql.Args() args: LikeFindManyArgs
  ): Promise<Like[]> {
    const results = await this.service.findLikes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Report], { name: "reports" })
  async findReports(
    @graphql.Parent() parent: Video,
    @graphql.Args() args: ReportFindManyArgs
  ): Promise<Report[]> {
    const results = await this.service.findReports(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(@graphql.Parent() parent: Video): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
