/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { CommentCreateNestedManyWithoutVideosInput } from "./CommentCreateNestedManyWithoutVideosInput";
import { Type } from "class-transformer";
import { LikeCreateNestedManyWithoutVideosInput } from "./LikeCreateNestedManyWithoutVideosInput";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { ReportCreateNestedManyWithoutVideosInput } from "./ReportCreateNestedManyWithoutVideosInput";

@InputType()
class VideoCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  caption?: string | null;

  @ApiProperty({
    required: false,
    type: () => CommentCreateNestedManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => CommentCreateNestedManyWithoutVideosInput)
  @IsOptional()
  @Field(() => CommentCreateNestedManyWithoutVideosInput, {
    nullable: true,
  })
  comments?: CommentCreateNestedManyWithoutVideosInput;

  @ApiProperty({
    required: false,
    type: () => LikeCreateNestedManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => LikeCreateNestedManyWithoutVideosInput)
  @IsOptional()
  @Field(() => LikeCreateNestedManyWithoutVideosInput, {
    nullable: true,
  })
  likes?: LikeCreateNestedManyWithoutVideosInput;

  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductWhereUniqueInput, {
    nullable: true,
  })
  product?: ProductWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReportCreateNestedManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => ReportCreateNestedManyWithoutVideosInput)
  @IsOptional()
  @Field(() => ReportCreateNestedManyWithoutVideosInput, {
    nullable: true,
  })
  reports?: ReportCreateNestedManyWithoutVideosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  retailer?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  thumbnailUrl?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  videoUrl?: string | null;
}

export { VideoCreateInput as VideoCreateInput };
