/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { CommentUpdateManyWithoutVideosInput } from "./CommentUpdateManyWithoutVideosInput";
import { Type } from "class-transformer";
import { LikeUpdateManyWithoutVideosInput } from "./LikeUpdateManyWithoutVideosInput";
import { ProductWhereUniqueInput } from "../../product/base/ProductWhereUniqueInput";
import { ReportUpdateManyWithoutVideosInput } from "./ReportUpdateManyWithoutVideosInput";

@InputType()
class VideoUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  caption?: string | null;

  @ApiProperty({
    required: false,
    type: () => CommentUpdateManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => CommentUpdateManyWithoutVideosInput)
  @IsOptional()
  @Field(() => CommentUpdateManyWithoutVideosInput, {
    nullable: true,
  })
  comments?: CommentUpdateManyWithoutVideosInput;

  @ApiProperty({
    required: false,
    type: () => LikeUpdateManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => LikeUpdateManyWithoutVideosInput)
  @IsOptional()
  @Field(() => LikeUpdateManyWithoutVideosInput, {
    nullable: true,
  })
  likes?: LikeUpdateManyWithoutVideosInput;

  @ApiProperty({
    required: false,
    type: () => ProductWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProductWhereUniqueInput)
  @IsOptional()
  @Field(() => ProductWhereUniqueInput, {
    nullable: true,
  })
  product?: ProductWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ReportUpdateManyWithoutVideosInput,
  })
  @ValidateNested()
  @Type(() => ReportUpdateManyWithoutVideosInput)
  @IsOptional()
  @Field(() => ReportUpdateManyWithoutVideosInput, {
    nullable: true,
  })
  reports?: ReportUpdateManyWithoutVideosInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  retailer?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  thumbnailUrl?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  videoUrl?: string | null;
}

export { VideoUpdateInput as VideoUpdateInput };
